import { useEffect, useRef, useState } from 'react'
import { Menu, X } from 'lucide-react'
import { ArrowUpRight, Github, Linkedin, Mail, MapPin, MessageCircle, Phone } from 'lucide-react'
import projects from '../assets/projects.json'
import training from '../assets/further_training.json'

const BG_IMAGE_1='https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260609_195923_b0ba8ace-1d1d-4f2c-9a28-1ab84b330680.png&w=1280&q=85'
const BG_IMAGE_2='https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260609_201152_bba90a12-bf12-459f-91f0-51f237dbaf3b.png&w=1280&q=85'
const SPOTLIGHT_R=260

const experience=[
  {role:'Data Science Intern',company:'Swiss International Air Lines',period:'Mar 2026 — Present',points:['Automating Python data pipelines for operational analytics.','Using Azure Data Factory and Blob Storage for scalable processing and deployment.','Building Power Automate workflows and analyzing Lufthansa Group ground operations data.','Supporting dashboards, stakeholder requirements, and data-quality checks during Azure migrations.']},
  {role:'Operations Specialist / AI Engineer',company:'The Brain Maze LLC',period:'Jul 2019 — Mar 2026',points:['Built a multi-stage generative AI production pipeline spanning scripts, text-to-speech, and image creation.','Automated the content production lifecycle with LLMs, reducing manual effort and increasing scalability.','Improved reporting workflows for stronger transparency and commercial visibility.']},
  {role:'Internship',company:'On AG',period:'Feb 2025 — Jan 2026',points:['Product Owner for cloud-based trade-compliance and legal automation.','Extracted and interpreted FTA rules with NLP and large language models.','Designed regulatory ETL pipelines with Python, SQL, and cloud-native services.','Connected legal experts, business stakeholders, and technical teams to drive adoption.']},
]

const skills: Array<[string,string|null]>=[
  ['Python','assets/pytorch.png'],['R',null],['SQL',null],['PyTorch','assets/pytorch.png'],['n8n','assets/n8n.png'],['Azure','assets/azure.png'],['Databricks','assets/databricks.png'],['Tableau','assets/tableau.png'],['Streamlit','assets/streamlit.png'],['Google Cloud',null],['Git',null],['GitHub',null],['LangChain','assets/langchain.png'],['Data Pipelines','assets/pipeline.png'],['Vertex AI','assets/vertexai.png'],
]

function RevealLayer({image,cursorX,cursorY}:{image:string;cursorX:number;cursorY:number}){
  const canvasRef=useRef<HTMLCanvasElement>(null)
  const revealRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const resize=()=>{canvas.width=window.innerWidth;canvas.height=window.innerHeight};resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[])
  useEffect(()=>{const canvas=canvasRef.current,reveal=revealRef.current;if(!canvas||!reveal)return;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createRadialGradient(cursorX,cursorY,0,cursorX,cursorY,SPOTLIGHT_R);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.4,'rgba(255,255,255,1)');g.addColorStop(.6,'rgba(255,255,255,.75)');g.addColorStop(.75,'rgba(255,255,255,.4)');g.addColorStop(.88,'rgba(255,255,255,.12)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cursorX,cursorY,SPOTLIGHT_R,0,Math.PI*2);ctx.fill();const mask=`url(${canvas.toDataURL()})`;reveal.style.maskImage=mask;reveal.style.webkitMaskImage=mask})
  return <><canvas ref={canvasRef} className="absolute inset-0 pointer-events-none" style={{display:'none'}}/><div ref={revealRef} className="absolute inset-0 bg-center bg-cover bg-no-repeat z-30 pointer-events-none" style={{backgroundImage:`url(${image})`,maskSize:'100% 100%',WebkitMaskSize:'100% 100%'}}/></>
}

function Logo(){return <div className="flex items-center gap-2.5"><svg width="26" height="26" viewBox="0 0 256 256" fill="#ffffff" aria-hidden="true"><path d="M 256 256 L 128 256 L 0 128 L 128 128 Z M 256 128 L 128 128 L 0 0 L 128 0 Z"/></svg><span className="text-white text-2xl font-playfair italic">Lithos</span></div>}

export default function App(){
  const mouse=useRef({x:-999,y:-999}),smooth=useRef({x:-999,y:-999}),rafRef=useRef<number>()
  const [cursorPos,setCursorPos]=useState({x:-999,y:-999}),[mobileOpen,setMobileOpen]=useState(false)
  useEffect(()=>{const move=(e:MouseEvent)=>{mouse.current={x:e.clientX,y:e.clientY}};const frame=()=>{smooth.current.x+=(mouse.current.x-smooth.current.x)*.1;smooth.current.y+=(mouse.current.y-smooth.current.y)*.1;setCursorPos({...smooth.current});rafRef.current=requestAnimationFrame(frame)};window.addEventListener('mousemove',move);rafRef.current=requestAnimationFrame(frame);return()=>{window.removeEventListener('mousemove',move);if(rafRef.current)cancelAnimationFrame(rafRef.current)}},[])
  const items=[['Projects','#projects'],['Experience','#experience'],['Education','#education'],['Skills','#skills'],['Contact','#contact']]
  return <div className="min-h-screen bg-white tracking-[-0.02em]" style={{fontFamily:"'Inter', sans-serif"}}>
    <nav className="fixed top-0 left-0 right-0 z-[100] flex items-center justify-between p-4 sm:p-5"><a href="#top" aria-label="Back to top"><Logo/></a><div className="hidden md:flex absolute left-1/2 -translate-x-1/2 bg-white/20 backdrop-blur-md border border-white/30 rounded-full px-2 py-2 items-center gap-1">{items.map(([item,href],i)=><a key={item} href={href} className={`px-4 py-1.5 rounded-full text-sm font-medium ${i===0?'bg-white text-gray-900':'text-white/80 hover:bg-white/20 hover:text-white transition-colors'}`}>{item}</a>)}</div><a href="https://www.linkedin.com/in/kened-kqiraj" target="_blank" rel="noreferrer" className="hidden md:block bg-white text-gray-900 text-sm font-semibold px-6 py-2.5 rounded-full hover:bg-gray-100">Let’s connect</a><button className="md:hidden grid place-items-center size-11 rounded-full bg-white/20 border border-white/30 backdrop-blur-md text-white" aria-label={mobileOpen?'Close navigation':'Open navigation'} aria-expanded={mobileOpen} onClick={()=>setMobileOpen(v=>!v)}>{mobileOpen?<X size={20}/>:<Menu size={20}/>}</button>{mobileOpen&&<div className="md:hidden absolute top-[72px] left-4 right-4 rounded-2xl border border-white/20 bg-black/85 p-2 backdrop-blur-xl">{items.map(([item,href])=><a key={item} href={href} onClick={()=>setMobileOpen(false)} className="block w-full rounded-xl px-4 py-3 text-left text-sm font-medium text-white/90 hover:bg-white/10">{item}</a>)}<a href="https://www.linkedin.com/in/kened-kqiraj" target="_blank" rel="noreferrer" className="mt-1 block w-full rounded-xl bg-white px-4 py-3 text-center text-sm font-semibold text-gray-900">Let’s connect</a></div>}</nav>
    <section id="top" className="relative w-full overflow-hidden h-screen bg-black" style={{height:'100dvh'}}><div className="absolute inset-0 z-10 bg-center bg-cover bg-no-repeat hero-zoom" style={{backgroundImage:`url(${BG_IMAGE_1})`}}/><RevealLayer image={BG_IMAGE_2} cursorX={cursorPos.x} cursorY={cursorPos.y}/><div className="absolute top-[14%] left-0 right-0 z-50 flex flex-col items-center text-center px-5 pointer-events-none"><p className="mb-5 text-[10px] font-semibold uppercase tracking-[.32em] text-white/60">Kened Kqiraj · Data Science & AI</p><h1 className="text-white leading-[0.95]"><span className="block font-playfair italic font-normal text-5xl sm:text-7xl md:text-8xl hero-anim hero-reveal" style={{letterSpacing:'-0.05em',animationDelay:'.25s'}}>Layers of data.</span><span className="block font-normal text-5xl sm:text-7xl md:text-8xl -mt-1 hero-anim hero-reveal" style={{letterSpacing:'-0.08em',animationDelay:'.42s'}}>Stories in motion.</span></h1></div><div className="hidden sm:block absolute bottom-14 left-10 md:left-14 z-50 max-w-[280px] hero-anim hero-fade" style={{animationDelay:'.7s'}}><p className="text-sm text-white/80 leading-relaxed">Based in Zug, Switzerland. MSc in Applied Information & Data Science, building intelligent systems from raw information.</p></div><div className="absolute bottom-10 sm:bottom-24 left-5 right-5 sm:left-auto sm:right-10 md:right-14 z-50 max-w-full sm:max-w-[280px] flex flex-col items-start gap-4 sm:gap-5 hero-anim hero-fade" style={{animationDelay:'.85s'}}><p className="text-xs sm:text-sm text-white/80 leading-relaxed">From cloud data pipelines to generative AI and trade-compliance automation, I turn complex material into useful decisions.</p><a href="#projects" className="bg-[#e8702a] hover:bg-[#d2611f] text-white text-sm font-medium px-7 py-3 rounded-full transition-all hover:scale-[1.03] active:scale-95 hover:shadow-lg hover:shadow-[#e8702a]/30">Explore my work</a></div></section>

    <main className="bg-[#0a0a09] text-[#f1eee7]">
      <section id="projects" className="portfolio-section"><SectionHead eyebrow="Selected specimens" title="Projects shaped from complex data"/><div className="grid gap-5 md:grid-cols-2">{projects.map((project)=><article key={project.title} className="stone-card group"><div className="flex items-start justify-between gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-white p-2"><img src={project.logo} alt="" className="max-h-7 max-w-7 object-contain"/></div><ArrowUpRight className="text-white/30 transition group-hover:text-[#e8702a]"/></div><h3 className="mt-8 text-2xl font-medium tracking-[-.04em]">{project.title.replace('â€”','—')}</h3><p className="mt-4 text-sm leading-6 text-white/55">{project.desc.replace('â€”','—')}</p><ul className="mt-6 space-y-2 border-t border-white/10 pt-5 text-xs leading-5 text-white/45">{project.bullets.slice(0,3).map(point=><li key={point}>— {point.replaceAll('â†’','→')}</li>)}</ul><div className="mt-6 flex flex-wrap gap-2">{project.tags.slice(0,5).map(tag=><span key={tag} className="rounded-full border border-white/10 px-3 py-1 text-[10px] uppercase tracking-wider text-white/50">{tag}</span>)}</div></article>)}</div></section>

      <section id="experience" className="portfolio-section border-t border-white/10"><SectionHead eyebrow="Professional strata" title="Experience built layer by layer"/><div className="divide-y divide-white/10 border-y border-white/10">{experience.map((job,index)=><article key={job.company} className="grid gap-5 py-9 md:grid-cols-[80px_1fr_1.4fr]"><span className="font-playfair text-3xl italic text-[#e8702a]">0{index+1}</span><div><h3 className="text-xl font-medium">{job.role}</h3><p className="mt-1 text-sm text-white/45">{job.company}<br/>{job.period}</p></div><ul className="space-y-2 text-sm leading-6 text-white/60">{job.points.map(point=><li key={point}>— {point}</li>)}</ul></article>)}</div></section>

      <section id="education" className="portfolio-section border-t border-white/10"><SectionHead eyebrow="Foundation" title="Education & field notes"/><div className="grid gap-5 lg:grid-cols-2"><div className="stone-card"><p className="section-label">Education</p><h3 className="mt-8 text-2xl">Master of Science</h3><p className="mt-2 text-white/55">Applied Information and Data Science<br/>Lucerne University of Applied Sciences and Arts</p><h3 className="mt-8 text-2xl">Bachelor of Accounting</h3><p className="mt-2 text-white/55">University of Prishtina · 2016</p></div><div id="training" className="stone-card"><p className="section-label">Further training</p><div className="mt-6 divide-y divide-white/10">{training.map(item=><div key={item.title} className="py-4"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-white/40">{item.org} · {item.period.replace('â€“','–')}</p></div>)}</div></div></div></section>

      <section id="skills" className="portfolio-section border-t border-white/10"><SectionHead eyebrow="Working toolkit" title="Technologies I work with"/><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-5">{skills.map(([name,icon])=><div key={name} className="flex min-h-28 flex-col items-center justify-center rounded-2xl border border-white/10 bg-white/[.025] p-4 text-center transition hover:border-[#e8702a]/50 hover:bg-white/[.05]">{icon?<img src={icon} alt="" className="mb-3 h-8 w-8 object-contain"/>:<span className="mb-3 font-playfair text-2xl italic text-[#e8702a]">{name.slice(0,2)}</span>}<span className="text-xs text-white/60">{name}</span></div>)}</div></section>

      <section id="contact" className="portfolio-section border-t border-white/10"><div className="rounded-[2rem] bg-[#e8702a] px-6 py-12 text-black sm:px-12 sm:py-16"><p className="section-label !text-black/50">Open to full-time roles</p><div className="mt-5 grid gap-10 lg:grid-cols-[1.4fr_1fr]"><h2 className="font-playfair text-5xl italic leading-none sm:text-7xl">Let’s build something useful.</h2><div className="flex flex-col items-start gap-3 text-sm font-medium"><a href="mailto:kened.kqiraj@hotmail.com" className="contact-link"><Mail size={17}/>kened.kqiraj@hotmail.com</a><a href="tel:+41765672985" className="contact-link"><Phone size={17}/>+41 76 567 29 85</a><span className="contact-link"><MapPin size={17}/>Zug, Switzerland</span><a href="https://www.linkedin.com/in/kened-kqiraj" target="_blank" rel="noreferrer" className="contact-link"><Linkedin size={17}/>LinkedIn</a><a href="https://github.com/kennedkqiraj" target="_blank" rel="noreferrer" className="contact-link"><Github size={17}/>GitHub</a><a href="https://kennedkqiraj-kennedkqiraj-github-io-app-llama-rag-agxxmo.streamlit.app/" target="_blank" rel="noreferrer" className="contact-link"><MessageCircle size={17}/>Chat with my assistant</a></div></div></div><footer className="flex flex-col gap-3 py-8 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Kened Kqiraj</span><span>Data Science · AI Engineering · Switzerland</span></footer></section>
    </main>
  </div>
}

function SectionHead({eyebrow,title}:{eyebrow:string;title:string}){return <div className="mb-12 grid gap-4 md:grid-cols-[1fr_2fr]"><p className="section-label">{eyebrow}</p><h2 className="max-w-3xl text-4xl leading-[1.05] tracking-[-.055em] sm:text-6xl">{title}</h2></div>}
