import { useEffect, useRef, useState } from 'react'
import { Menu, X } from 'lucide-react'

const BG_IMAGE_1='https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260609_195923_b0ba8ace-1d1d-4f2c-9a28-1ab84b330680.png&w=1280&q=85'
const BG_IMAGE_2='https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260609_201152_bba90a12-bf12-459f-91f0-51f237dbaf3b.png&w=1280&q=85'
const SPOTLIGHT_R=260

function RevealLayer({image,cursorX,cursorY}:{image:string;cursorX:number;cursorY:number}){
  const canvasRef=useRef<HTMLCanvasElement>(null)
  const revealRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const resize=()=>{canvas.width=window.innerWidth;canvas.height=window.innerHeight};resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[])
  useEffect(()=>{const canvas=canvasRef.current,reveal=revealRef.current;if(!canvas||!reveal)return;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createRadialGradient(cursorX,cursorY,0,cursorX,cursorY,SPOTLIGHT_R);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.4,'rgba(255,255,255,1)');g.addColorStop(.6,'rgba(255,255,255,.75)');g.addColorStop(.75,'rgba(255,255,255,.4)');g.addColorStop(.88,'rgba(255,255,255,.12)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cursorX,cursorY,SPOTLIGHT_R,0,Math.PI*2);ctx.fill();const mask=`url(${canvas.toDataURL()})`;reveal.style.maskImage=mask;reveal.style.webkitMaskImage=mask})
  return <><canvas ref={canvasRef} className="absolute inset-0 pointer-events-none" style={{display:'none'}}/><div ref={revealRef} className="absolute inset-0 bg-center bg-cover bg-no-repeat z-30 pointer-events-none" style={{backgroundImage:`url(${image})`,maskSize:'100% 100%',WebkitMaskSize:'100% 100%'}}/></>
}

function Logo(){return <div className="flex items-center gap-2.5"><svg width="26" height="26" viewBox="0 0 256 256" fill="#ffffff" aria-hidden="true"><path d="M 256 256 L 128 256 L 0 128 L 128 128 Z M 256 128 L 128 128 L 0 0 L 128 0 Z"/></svg><span className="text-white text-2xl font-playfair italic">Lithos</span></div>}

export default function App(){
  const mouse=useRef({x:-999,y:-999}),smooth=useRef({x:-999,y:-999}),rafRef=useRef<number>()
  const [cursorPos,setCursorPos]=useState({x:-999,y:-999}),[mobileOpen,setMobileOpen]=useState(false)
  useEffect(()=>{const move=(e:MouseEvent)=>{mouse.current={x:e.clientX,y:e.clientY}};const frame=()=>{smooth.current.x+=(mouse.current.x-smooth.current.x)*.1;smooth.current.y+=(mouse.current.y-smooth.current.y)*.1;setCursorPos({...smooth.current});rafRef.current=requestAnimationFrame(frame)};window.addEventListener('mousemove',move);rafRef.current=requestAnimationFrame(frame);return()=>{window.removeEventListener('mousemove',move);if(rafRef.current)cancelAnimationFrame(rafRef.current)}},[])
  const items=['Course','Field Guides','Geology','Plans','Live Tour']
  return <div className="min-h-screen bg-white tracking-[-0.02em]" style={{fontFamily:"'Inter', sans-serif"}}>
    <nav className="fixed top-0 left-0 right-0 z-[100] flex items-center justify-between p-4 sm:p-5"><Logo/><div className="hidden md:flex absolute left-1/2 -translate-x-1/2 bg-white/20 backdrop-blur-md border border-white/30 rounded-full px-2 py-2 items-center gap-1">{items.map((item,i)=><button key={item} className={`px-4 py-1.5 rounded-full text-sm font-medium ${i===0?'bg-white text-gray-900':'text-white/80 hover:bg-white/20 hover:text-white transition-colors'}`}>{item}</button>)}</div><button className="hidden md:block bg-white text-gray-900 text-sm font-semibold px-6 py-2.5 rounded-full hover:bg-gray-100">Sign Up</button><button className="md:hidden grid place-items-center size-11 rounded-full bg-white/20 border border-white/30 backdrop-blur-md text-white" aria-label={mobileOpen?'Close navigation':'Open navigation'} aria-expanded={mobileOpen} onClick={()=>setMobileOpen(v=>!v)}>{mobileOpen?<X size={20}/>:<Menu size={20}/>}</button>{mobileOpen&&<div className="md:hidden absolute top-[72px] left-4 right-4 rounded-2xl border border-white/20 bg-black/75 p-2 backdrop-blur-xl">{items.map(item=><button key={item} className="block w-full rounded-xl px-4 py-3 text-left text-sm font-medium text-white/90 hover:bg-white/10">{item}</button>)}<button className="mt-1 w-full rounded-xl bg-white px-4 py-3 text-sm font-semibold text-gray-900">Sign Up</button></div>}</nav>
    <section className="relative w-full overflow-hidden h-screen bg-black" style={{height:'100dvh'}}><div className="absolute inset-0 z-10 bg-center bg-cover bg-no-repeat hero-zoom" style={{backgroundImage:`url(${BG_IMAGE_1})`}}/><RevealLayer image={BG_IMAGE_2} cursorX={cursorPos.x} cursorY={cursorPos.y}/><div className="absolute top-[14%] left-0 right-0 z-50 flex flex-col items-center text-center px-5 pointer-events-none"><h1 className="text-white leading-[0.95]"><span className="block font-playfair italic font-normal text-5xl sm:text-7xl md:text-8xl hero-anim hero-reveal" style={{letterSpacing:'-0.05em',animationDelay:'.25s'}}>Layers hold</span><span className="block font-normal text-5xl sm:text-7xl md:text-8xl -mt-1 hero-anim hero-reveal" style={{letterSpacing:'-0.08em',animationDelay:'.42s'}}>tales of time</span></h1></div><div className="hidden sm:block absolute bottom-14 left-10 md:left-14 z-50 max-w-[260px] hero-anim hero-fade" style={{animationDelay:'.7s'}}><p className="text-sm text-white/80 leading-relaxed">Every layer of sediment records a chapter of our planet, from ancient seabeds to drifting ash, layered across millions of years beneath us.</p></div><div className="absolute bottom-10 sm:bottom-24 left-5 right-5 sm:left-auto sm:right-10 md:right-14 z-50 max-w-full sm:max-w-[260px] flex flex-col items-start gap-4 sm:gap-5 hero-anim hero-fade" style={{animationDelay:'.85s'}}><p className="text-xs sm:text-sm text-white/80 leading-relaxed">Our interactive maps let you peel back the crust to trace how stones, fossils, and deep time combine to shape the ground beneath your feet.</p><button className="bg-[#e8702a] hover:bg-[#d2611f] text-white text-sm font-medium px-7 py-3 rounded-full transition-all hover:scale-[1.03] active:scale-95 hover:shadow-lg hover:shadow-[#e8702a]/30">Start Digging</button></div></section>
  </div>
}
